services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-open-aero-dream
    environment:
      - 'POSTGRES_DB=aerodream'
      - 'POSTGRES_PASSWORD=12345'
    ports:
      - '5432:5432'
